services:
  postgres:
    image: postgres:16
    container_name: postgres_lab_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: labuser
      POSTGRES_PASSWORD: labpass
      POSTGRES_DB: lab_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
